apiVersion: apps/v1
kind: Deployment
metadata:
  name: moveservice
  labels:
    run: moveservice
spec:
  replicas: 1
  selector:
    matchLabels:
      run: moveservice
  template:
    metadata:
      labels:
        run: moveservice
    spec:
      containers:
        - name: moveservice
          image: christopherjunk/moveservice
          ports:
            - containerPort: 1024