apiVersion: apps/v1
kind: Deployment
metadata:
  name: moveservice
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: moveservice
      containers:
        - name: moveservice
          image: christopherjunk/moveservice
          ports:
            - containerPort: 1024
          volumeMounts:
          - mountPath: /moveservice-logs
            name: vol