apiVersion: apps/v1
kind: Deployment
metadata:
  name: evalservice
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: evalservice
          image: christopherjunk/evalservice
          ports:
            - containerPort: 1025