apiVersion: apps/v1
kind: Deployment
metadata:
  name: evalservice
  labels:
    run: evalservice
spec:
  replicas: 3
  selector:
    matchLabels:
      run: evalservice
  template:
    metadata:
      labels:
        run: evalservice
    spec:
      containers:
        - name: evalservice
          image: christopherjunk/evalservice
          ports:
            - containerPort: 1025