apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moveservice
  labels:
    cchess: moveservice
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Mi
  volumeName: cchess-logs-node-b
